INSERT INTO TIP_ORGANIZACIJSKE_JEDINICE (NAZIV, AKTIVAN) VALUES ('REGIJA', true);
INSERT INTO TIP_ORGANIZACIJSKE_JEDINICE (NAZIV, AKTIVAN) VALUES ('ŽUPANIJA', true);

INSERT INTO VELICINA_GRADA (NAZIV, AKTIVAN) VALUES ('Mali', true);
INSERT INTO VELICINA_GRADA (NAZIV, AKTIVAN) VALUES ('Srednji', true);
INSERT INTO VELICINA_GRADA (NAZIV, AKTIVAN) VALUES ('Velik', true);

--Regije
INSERT INTO ORGANIZACIJSKA_JEDINICA (NAZIV, OPIS, TIP_ORG_JED_ID) VALUES ('Centralna Hrvatska', 'Centralni dio Republike Hrvatske. Najveći grad je Zagreb, glavni grad Hrvatske.', 1);
INSERT INTO ORGANIZACIJSKA_JEDINICA (NAZIV, OPIS, TIP_ORG_JED_ID) VALUES ('Istočna Hrvatska', 'Regija je glavna žitnica i poljoprivredno najrazvijeniji dio Hrvatske.', 1);
INSERT INTO ORGANIZACIJSKA_JEDINICA (NAZIV, OPIS, TIP_ORG_JED_ID) VALUES ('Planinska Hrvatska', 'Planinska Hrvatska', 1);
INSERT INTO ORGANIZACIJSKA_JEDINICA (NAZIV, OPIS, TIP_ORG_JED_ID) VALUES ('Sjeverna Hrvatska obala', 'Sjeverna Hrvatska obala', 1);
INSERT INTO ORGANIZACIJSKA_JEDINICA (NAZIV, OPIS, TIP_ORG_JED_ID) VALUES ('Južna Hrvatska obala', 'Južna Hrvatska obala', 1);

--Županije
INSERT INTO ORGANIZACIJSKA_JEDINICA (NAZIV, OPIS, ORG_JED_ID, TIP_ORG_JED_ID) VALUES ('Međimurska', 'Međimurska Županija', 1, 2);
INSERT INTO ORGANIZACIJSKA_JEDINICA (NAZIV, OPIS, ORG_JED_ID, TIP_ORG_JED_ID) VALUES ('Varaždinska', 'Varaždinska Županija', 1, 2);
INSERT INTO ORGANIZACIJSKA_JEDINICA (NAZIV, OPIS, ORG_JED_ID, TIP_ORG_JED_ID) VALUES ('Zagrebačka', 'Zagrebačka Županija', 1, 2);
INSERT INTO ORGANIZACIJSKA_JEDINICA (NAZIV, OPIS, ORG_JED_ID, TIP_ORG_JED_ID) VALUES ('Grad Zagreb', 'Grad Zagreb', 1, 2);
INSERT INTO ORGANIZACIJSKA_JEDINICA (NAZIV, OPIS, ORG_JED_ID, TIP_ORG_JED_ID) VALUES ('Osječko-Baranjska', 'Osječko-Baranjska županija', 2, 2);
INSERT INTO ORGANIZACIJSKA_JEDINICA (NAZIV, OPIS, ORG_JED_ID, TIP_ORG_JED_ID) VALUES ('Brodsko-Posavska', 'Brodsko-Posavska županija', 2, 2);
INSERT INTO ORGANIZACIJSKA_JEDINICA (NAZIV, OPIS, ORG_JED_ID, TIP_ORG_JED_ID) VALUES ('Virovitičko-Podravska', 'Virovitičko-Podravska županija', 2, 2);
INSERT INTO ORGANIZACIJSKA_JEDINICA (NAZIV, OPIS, ORG_JED_ID, TIP_ORG_JED_ID) VALUES ('Ličko-Senjska', 'Ličko-Senjska županija', 3, 2);
INSERT INTO ORGANIZACIJSKA_JEDINICA (NAZIV, OPIS, ORG_JED_ID, TIP_ORG_JED_ID) VALUES ('Istarska', 'Istarska ', 4, 2);
INSERT INTO ORGANIZACIJSKA_JEDINICA (NAZIV, OPIS, ORG_JED_ID, TIP_ORG_JED_ID) VALUES ('Splitsko-Dalmatinska', 'Splitsko-Dalmatinska županija', 5, 2);
INSERT INTO ORGANIZACIJSKA_JEDINICA (NAZIV, OPIS, ORG_JED_ID, TIP_ORG_JED_ID) VALUES ('Dubrovačko-Neretvanska', 'Splitsko-Dalmatinska županija', 5, 2);

--Gradovi
INSERT INTO GRAD (NAZIV, VELICINA_GRADA_ID, ORG_JED_ID) VALUES ('Čakovec', 2, 6);
INSERT INTO GRAD (NAZIV, VELICINA_GRADA_ID, ORG_JED_ID) VALUES ('Varaždin', 2, 7);
INSERT INTO GRAD (NAZIV, VELICINA_GRADA_ID, ORG_JED_ID) VALUES ('Ivanić Grad', 1, 8);
INSERT INTO GRAD (NAZIV, VELICINA_GRADA_ID, ORG_JED_ID) VALUES ('Zagreb', 3, 9);
INSERT INTO GRAD (NAZIV, VELICINA_GRADA_ID, ORG_JED_ID) VALUES ('Osijek', 3, 10);
INSERT INTO GRAD (NAZIV, VELICINA_GRADA_ID, ORG_JED_ID) VALUES ('Slavonski Brod', 2, 11);
INSERT INTO GRAD (NAZIV, VELICINA_GRADA_ID, ORG_JED_ID) VALUES ('Virovitica', 2, 12);
INSERT INTO GRAD (NAZIV, VELICINA_GRADA_ID, ORG_JED_ID) VALUES ('Senj', 2, 13);
INSERT INTO GRAD (NAZIV, VELICINA_GRADA_ID, ORG_JED_ID) VALUES ('Pula', 2, 14);
INSERT INTO GRAD (NAZIV, VELICINA_GRADA_ID, ORG_JED_ID) VALUES ('Split', 3, 15);
INSERT INTO GRAD (NAZIV, VELICINA_GRADA_ID, ORG_JED_ID) VALUES ('Dubrovnik', 2, 16);

--Događaji
INSERT INTO DOGADJAJI (NAZIV, VRIJEME_OD, VRIJEME_DO, SLOBODAN_ULAZ, GRAD_ID) VALUES ('Ultra festival', '2019-07-28 21:00:00', '2019-07-29 21:00:00', false, 10);
INSERT INTO DOGADJAJI (NAZIV, VRIJEME_OD, VRIJEME_DO, SLOBODAN_ULAZ, GRAD_ID) VALUES ('Rujan fest', '2019-09-15 21:00:00', '2019-09-22 21:00:00', true, 4);
INSERT INTO DOGADJAJI (NAZIV, VRIJEME_OD, VRIJEME_DO, SLOBODAN_ULAZ, GRAD_ID) VALUES ('Lejdi Gaga', '2022-05-15 21:00:00', '2022-05-16 02:00:00', false, 4);
INSERT INTO DOGADJAJI (NAZIV, VRIJEME_OD, VRIJEME_DO, SLOBODAN_ULAZ, GRAD_ID) VALUES ('Špancirfest', '2019-09-15 21:00:00', '2022-09-20 02:00:00', true, 2);
INSERT INTO DOGADJAJI (NAZIV, VRIJEME_OD, VRIJEME_DO, SLOBODAN_ULAZ, GRAD_ID) VALUES ('Dani krumpira i zelja', '2019-10-15 21:00:00', '2022-10-20 02:00:00', true, 1);
INSERT INTO DOGADJAJI (NAZIV, VRIJEME_OD, VRIJEME_DO, SLOBODAN_ULAZ, GRAD_ID) VALUES ('Dani jedenja bundeva', '2019-11-15 21:00:00', '2022-11-20 02:00:00', true, 3);
INSERT INTO DOGADJAJI (NAZIV, VRIJEME_OD, VRIJEME_DO, SLOBODAN_ULAZ, GRAD_ID) VALUES ('Panonian Challenge', '2020-06-15 21:00:00', '2020-06-17 02:00:00', true, 5);
INSERT INTO DOGADJAJI (NAZIV, VRIJEME_OD, VRIJEME_DO, SLOBODAN_ULAZ, GRAD_ID) VALUES ('Kuhanje fišpaprikaša', '2019-12-15 21:00:00', '2019-12-17 02:00:00', true, 6);
INSERT INTO DOGADJAJI (NAZIV, VRIJEME_OD, VRIJEME_DO, SLOBODAN_ULAZ, GRAD_ID) VALUES ('Koncert Šima Jovanovac', '2019-12-31 21:00:00', '2020-01-01 02:00:00', true, 7);
INSERT INTO DOGADJAJI (NAZIV, VRIJEME_OD, VRIJEME_DO, SLOBODAN_ULAZ, GRAD_ID) VALUES ('Josipa Lisac u Areni', '2019-08-31 21:00:00', '2019-09-01 02:00:00', false, 9);
INSERT INTO DOGADJAJI (NAZIV, VRIJEME_OD, VRIJEME_DO, SLOBODAN_ULAZ, GRAD_ID) VALUES ('Dubrovačke Ljetne Igre', '2019-07-01 21:00:00', '2019-07-07 02:00:00', false, 11);
