
CREATE TABLE IF NOT EXISTS TIP_ORGANIZACIJSKE_JEDINICE (
	ID int AUTO_INCREMENT PRIMARY KEY,
	NAZIV varchar(100) NOT NULL,
	AKTIVAN boolean NOT NULL
);

CREATE TABLE IF NOT EXISTS VELICINA_GRADA (
	ID int AUTO_INCREMENT PRIMARY KEY,
	NAZIV varchar(100) NOT NULL,
	AKTIVAN boolean NOT NULL
);

CREATE TABLE IF NOT EXISTS ORGANIZACIJSKA_JEDINICA (
	ID int AUTO_INCREMENT PRIMARY KEY,
	NAZIV varchar(100) NOT NULL,
	OPIS varchar(200),
	ORG_JED_ID int,
	TIP_ORG_JED_ID int,
	FOREIGN KEY (ORG_JED_ID) REFERENCES ORGANIZACIJSKA_JEDINICA(ID),
	FOREIGN KEY (TIP_ORG_JED_ID) REFERENCES TIP_ORGANIZACIJSKE_JEDINICE(ID)	
);

CREATE TABLE IF NOT EXISTS GRAD (
	ID int AUTO_INCREMENT PRIMARY KEY,
	NAZIV varchar(100) NOT NULL,
	VELICINA_GRADA_ID int NOT NULL,
	ORG_JED_ID int NOT NULL,
	FOREIGN KEY (VELICINA_GRADA_ID) REFERENCES VELICINA_GRADA(ID),
	FOREIGN KEY (ORG_JED_ID) REFERENCES ORGANIZACIJSKA_JEDINICA(ID),
	
);

CREATE TABLE IF NOT EXISTS DOGADJAJI (
	ID int AUTO_INCREMENT PRIMARY KEY, 
	NAZIV varchar(100) NOT NULL,
	VRIJEME_OD timestamp NOT NULL,
	VRIJEME_DO timestamp,
	SLOBODAN_ULAZ boolean NOT NULL,
	GRAD_ID int,
	FOREIGN KEY (GRAD_ID) REFERENCES GRAD(ID)
);